---
# This playbook contains common plays that will be run on all nodes.

- include: centos.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
