---
# This playbook contains common plays that will be run on all nodes.

- name: Update the apt repo before we start
  apt: update-cache=yes
       cache_valid_time=36000

- name: "{{ role }}: Install python apps that ansible needs"
  command: apt-get install {{ item }}
  with_items: 
    - python-apt
    - python-paramiko
    - python-selinux
  changed_when: False

- name: Set timezone variables
  copy: content='America/Chicago'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update_ubuntu_timezone
