---
# This play is for PackStack

- name: "Check if /root/keystonerc_admin exists. Remove file to force rebuild."
  stat: path=/root/keystonerc_admin
  register: keystone_admin

#-------------------------------------------------------------------------------
#- Preliminary System Setup, get the network services in shape etc...
#- Install Packstack packages.
#- Requirements: Must have a system with minimum 3GB RAM
#-------------------------------------------------------------------------------

- name: "Set SELINUX"
  selinux: policy=targeted state=permissive
  when: not keystone_admin.stat.exists

- name: "Disable Network Services, but leave it running during configuration!"
  service: name={{ item }}
           enabled=no
           # state=stopped: Packstack somehow needs it to be running.
  with_items:
    - NetworkManager
    - firewalld
  register: nm
  ignore_errors: true
  when: not keystone_admin.stat.exists


- name: "Enable the *SANE* networking service"
  service: name={{ item }}
           enabled=yes
  with_items:
    - network
  when: not keystone_admin.stat.exists

- name: "Uninstall Bad Packages"
  yum: name={{ item }}
       state=installed
  with_items:
    - firewalld
  when: not keystone_admin.stat.exists

- name: "Install RDO Repo"
  yum: state=installed
       name=https://rdo.fedorapeople.org/rdo-release.rpm
  when: not keystone_admin.stat.exists

- name: "Update Yum Cache"
  yum: name=* state=latest
  when: not keystone_admin.stat.exists

- name: "Install Packstack Packages"
  yum: state=installed
       name={{ item }}
  with_items:
    - openstack-packstack
  ignore_errors: true
  when: not keystone_admin.stat.exists

#-------------------------------------------------------------------------------
# MongoDB has an error in its puppet setup.
# It may not be needed later, but it is now for Centos7.
#-------------------------------------------------------------------------------
- name: "Fix the MongoDB Puppet entry for PID file"
  lineinfile: dest=/usr/lib/python2.7/site-packages/packstack/puppet/templates/mongodb.pp
              line="   pidfilepath  => '/var/run/mongodb/mongod.pid',"
              insertafter='^\s+bind_ip.*$'
              state=present
  when: not keystone_admin.stat.exists

#-------------------------------------------------------------------------------
#- Reboot the Server so that network can start working properly
#-------------------------------------------------------------------------------

- name: "Reboot Server"
  sudo: true
  command: reboot
  ignore_errors: true
  when: nm.changed == true and not keystone_admin.stat.exists

- name: "waiting for server to come back"
  sudo: false
  local_action: wait_for
                host={{ inventory_hostname }}
                port=22
                state=started
                delay=10
  when: nm.changed == true and not keystone_admin.stat.exists

#-------------------------------------------------------------------------------
#- Packstack Configuration
#-------------------------------------------------------------------------------

- name: "Run Packstack Installer"
  command: packstack
           --allinone
           --provision-all-in-one-ovs-bridge=n
           --provision-demo=n
           --default-password={{ keystone.OS_PASSWORD }}
  args:
    creates: /root/keystonerc_admin
  when: not keystone_admin.stat.exists

#-------------------------------------------------------------------------------
#- External Network Configuration to allow Access to/from internal VMs
#-------------------------------------------------------------------------------

- name: "Setup Bridge interfaces."
  template: src={{ item.source }}
            dest=/etc/sysconfig/network-scripts/{{ item.dest }}
  with_items:
    - { source: 'ifcfg-br-ex', dest: 'ifcfg-br-ex' }
    - { source: 'ifcfg-if',    dest: 'ifcfg-{{hardware.if.name}}' }
  register: bridge_setup
  when: not keystone_admin.stat.exists

- name: "Restart networking service"
  service: name=network state=restarted
  when: bridge_setup.changed == true

#===============================================================================
#  Reconfigure various Openstack/Neutron items
#===============================================================================
 
# /root/keystonerc_admin should now exist and Packstack should be ready
- name: "Re-Check if /root/keystonerc_admin exists. Reconfigure OS if exists."
  stat: path=/root/keystonerc_admin
  register: keystone_admin_post

- name: "Add/Append plugins to neutron.conf"
  command: openstack-config --list --set /etc/neutron/neutron.conf 
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: neutron_plugins_extra
  when: keystone_admin_post.stat.exists

- name: "Fix libvirt hyervisor; Use openstack-config to configure nova.conf"
  command: openstack-config --set /etc/nova/nova.conf
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: nova_conf
  when: keystone_admin_post.stat.exists

- name: "Setup neutron/ml2 plugin.ini"
  command: openstack-config --set /etc/neutron/plugin.ini
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: neutron_ml2_plugin
  register: ml2_setup
  when: keystone_admin_post.stat.exists

- name: "Set openvswitch settings"
  command: openstack-config --set /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: ovs_neutron_plugin
  register: openvswitch_setup
  when: keystone_admin_post.stat.exists

- name: "Set L3 settings"
  command: openstack-config --set /etc/neutron/l3_agent.ini
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: neutron_l3_agent
  register: l3_setup
  when: keystone_admin_post.stat.exists

- name: "Temporary Fix bug 1385908 in neutronclient api. "
  replace: 
    dest: "/usr/lib/python2.7/site-packages/neutronclient/neutron/v2_0/fw/firewallpolicy.py"
    regexp: "'--firewall-rules', type=str.split"
    replace: "'--firewall-rules', type=lambda x: x.split()"
  when: keystone_admin_post.stat.exists

- name: "Bounce nova/neutron"
  service: name={{item}}
           state=restarted
  with_items: nova_services + neutron_services
  when: keystone_admin_post.stat.exists

#-------------------------------------------------------------------------------
#- Configure RabbitMQ, Zenoss_dispatcher, Ceilometer, etc..
#-------------------------------------------------------------------------------

# Broken in current version: ansible looks for missing sbin
# - name: Enable RabbitMQ rabbitmq_management
#   rabbitmq_plugin: names=rabbitmq_management
#                    state=enabled
#                    new_only=yes
#                    prefix=/usr/lib/rabbitmq
#  when: keystone_admin_post.stat.exists

- name: "Enable RabbitMQ rabbitmq_management with command"
  command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management
  when: keystone_admin_post.stat.exists

- name: "Install Zenoss plugin for dispatcher_zenoss"
  pip: name=https://github.com/zenoss/ceilometer_zenoss/archive/master.zip
  when: keystone_admin_post.stat.exists

- name: "stat ceilometer_zenoss/event_definitions.yaml"
  stat: path=/usr/lib/python2.7/site-packages/ceilometer_zenoss/event_definitions.yaml
  register: ceilometer_event_definitions
  when: keystone_admin_post.stat.exists

- name: "copy ceilometer_zenoss/event_definitions.yaml"
  command: cp /usr/lib/python2.7/site-packages/ceilometer_zenoss/event_definitions.yaml /etc/ceilometer/
  when: ceilometer_event_definitions.stat.exists and keystone_admin_post.stat.exists

- name: "Modify /etc/ceilometer/ceilometer.conf to add event_defs with replace"
  replace: dest=/etc/ceilometer/ceilometer.conf
           regexp='^#dispatcher=database'
           replace='dispatcher=database\ndispatcher=zenoss'
  when: keystone_admin_post.stat.exists

- name: "Modify /etc/ceilometer/pipeline.yaml: set interval to 300s"
  replace: "dest=/etc/ceilometer/pipeline.yaml
            regexp='interval: 600$'
            replace='interval: 300'"
  when: keystone_admin_post.stat.exists

#-------------------------------------------------------------------------------
# Configure Ceilomater
#-------------------------------------------------------------------------------
- name: "Use openstack-config to configure ceilometer"
  command: openstack-config --set /etc/ceilometer/ceilometer.conf
           {{item.section}}
           {{item.parameter}}
           {{item.value}}
  with_items: ceilometer_cfg
  when: keystone_admin_post.stat.exists

- name: "Bounce ceilometer"
  service: name={{item}}
           state=restarted
  with_items: ceilometer_services
  when: keystone_admin_post.stat.exists

